services:
  cloud:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CURRENT_API_BASE_URL
    restart: always
    expose:
      - '3000'
    depends_on:
      cloud-db:
        condition: service_healthy
    container_name: greact-drill-cloud-${BRANCH}
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - CURRENT_API_BASE_URL=${CURRENT_API_BASE_URL}
    networks:
      - proxy

  cloud-db:
    image: postgres:17
    container_name: cloud-database-container
    restart: always
    expose:
      - '5432'
    volumes:
      - cloud-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  cloud-db:

networks:
  proxy:
    external: true
